services:
  db:
    image: cats_log/mysql:1.0 # 変更
    build:
      context: .
      dockerfile: ./db/Dockerfile
    container_name: "db_cats_log" # 変更
    platform: linux/x86_64
    expose:
      - "3306"
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my
      - MYSQL_USER=my
      - MYSQL_PASSWORD=my
    volumes:
      - db_data:/var/lib/mysql # ホスト：コンテナ
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      # ヘルスチェックのインターバルは10秒
      interval: 10s
      # タイムアウト時間は10秒
      timeout: 10s
      # リトライ回数は3回
      retries: 3
      # ヘルスチェックが失敗しても無視する時間は30秒
      start_period: 30s
  app:
    image: cats_log/app:1.0 # 変更
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: "app_cats_log" # 変更
    ports:
      - 8080:8080 # ホスト：コンテナ
    # command: python3 /home/user1/dev/manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        # dbのヘルスチェックが終わってからappを起動させる
        condition: service_healthy
    stdin_open: true
    tty: true
    volumes:
      - ../app:/home/user1/dev
volumes:
  db_data:
